import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Film, Plus, Trash2, Copy, Check, ChevronDown, ChevronUp, Wand2, Download, RefreshCw, Camera, Mic, Subtitles, Scissors } from "lucide-react";
import { toast } from "sonner";
import type { SelfMediaStore } from "@/hooks/useSelfMediaStore";
import type { Script, Shot, ContentType } from "@/data/selfmedia3-types";
import { AIDisconnectedBanner, EmptyState, FactConfirmTag } from "./shared";
import { callAI, extractJSON } from "@/lib/aiService";
import { loadAIConfig } from "@/lib/aiConfig";

const CONTENT_TYPES: ContentType[] = ["老板娘口播", "菜品制作", "后厨实拍", "日常vlog", "食材科普", "门店展示", "故事讲述", "团购推荐", "图文笔记"];
const emptyShot = (n:number): Shot => ({ shotNumber:n,time:"",shotSize:"中景",visual:"",action:"",dialogue:"",subtitle:"",sound:"自然环境声 + 轻BGM",shootingNote:"不拍客人",editingNote:"",isRequired:true,status:"未拍" });

interface Props { store: SelfMediaStore; currentDay?: number; }

export default function ScriptDirectorPanel({ store, currentDay = 1 }: Props) {
  const [activeId,setActiveId]=useState<string|null>(null);
  const [showMeta,setShowMeta]=useState(true);
  const [busy,setBusy]=useState(false);
  const filtered=store.scripts.filter(s=>s.accountId===store.currentAccount&&s.storeId===store.currentStore);
  const dayScripts=filtered.filter(s=>s.day===currentDay).sort((a,b)=>b.createdAt-a.createdAt);
  const dayTopic=store.topics.filter(t=>t.accountId===store.currentAccount&&t.storeId===store.currentStore&&t.day===currentDay).sort((a,b)=>b.createdAt-a.createdAt)[0]||null;
  const active=filtered.find(s=>s.id===activeId)||dayScripts[0]||filtered[0]||null;
  const sourceTopic=active?.sourceTopicId?store.topics.find(t=>t.id===active.sourceTopicId):dayTopic;

  const update=(patch:Partial<Script>)=>{if(active)store.updateScript(active.id,{...patch,updatedAt:Date.now()});};
  const newScript=()=>{const s=store.addScript({title:"新脚本",targetUser:"",goal:"",person:"老板娘",dish:"",estimatedDuration:"45秒",contentType:"老板娘口播",shots:[emptyShot(1),emptyShot(2),emptyShot(3)],requiredMediaIds:[],shootingOrder:"",requiredShots:"",optionalShots:"",missingMaterials:"",status:"草稿",createdAt:Date.now(),updatedAt:Date.now()});setActiveId(s.id);};
  const makeToday=()=>{if(!dayTopic){toast.error("今天还没有选题");return;}const s=store.createScriptFromTopic(dayTopic,currentDay);if(s)setActiveId(s.id);};
  const copy=()=>{if(!active)return;const s=store.addScript({...active,title:`${active.title}（副本）`,status:"草稿",createdAt:Date.now(),updatedAt:Date.now()} as Omit<Script,"id"|"accountId"|"storeId">);setActiveId(s.id);toast.success("脚本已复制");};
  const remove=()=>{if(!active)return;if(confirm(`确定删除《${active.title}》吗？`)){store.removeScript(active.id);setActiveId(null);}};
  const updateShot=(i:number,p:Partial<Shot>)=>{if(!active)return;const shots=active.shots.map((x,n)=>n===i?{...x,...p}:x);update({shots});};

  const download=()=>{if(!active)return;const text=[`《${active.title}》`,`目标用户：${active.targetUser}`,`目标：${active.goal}`,`人物：${active.person}`,`菜品：${active.dish||"—"}`,`时长：${active.estimatedDuration}`,`类型：${active.contentType}`,"","【逐镜头拍摄执行表】",...active.shots.map(x=>[`镜头${x.shotNumber}｜${x.time}｜${x.shotSize}｜${x.isRequired?"必拍":"可选"}`,`画面：${x.visual}`,`动作：${x.action}`,`台词：${x.dialogue}`,`字幕：${x.subtitle}`,`声音/BGM：${x.sound}`,`拍摄备注：${x.shootingNote}`,`剪辑备注：${x.editingNote}`,""].join("\n")),`拍摄顺序：${active.shootingOrder}`,`必拍：${active.requiredShots}`,`可选：${active.optionalShots}`,`缺失素材：${active.missingMaterials}`].join("\n");const blob=new Blob([text],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${active.title||"短视频脚本"}_完整拍摄执行表.txt`;a.click();URL.revokeObjectURL(url);toast.success("完整脚本已下载");};

  const aiGenerate=async(action:string)=>{if(!active||busy)return;setBusy(true);try{const context=sourceTopic?`选题：${sourceTopic.title}\nHook：${sourceTopic.hook}\n痛点：${sourceTopic.painPoint}\n核心观点：${sourceTopic.coreOpinion}\n结构：${sourceTopic.structure}\nCTA：${sourceTopic.cta}\n推荐菜品：${sourceTopic.recommendedDish}`:"";const current=JSON.stringify({title:active.title,targetUser:active.targetUser,goal:active.goal,person:active.person,dish:active.dish,estimatedDuration:active.estimatedDuration,contentType:active.contentType,shots:active.shots});const prompt=`你是餐饮实体店短视频现场导演。请直接完成：${action}。\n${context}\n当前脚本：${current}\n\n必须输出严格JSON，不要Markdown。JSON必须包含 title,targetUser,goal,person,dish,estimatedDuration,contentType,shots,shootingOrder,requiredShots,optionalShots,missingMaterials。shots生成8-12个镜头，每个镜头包含shotNumber,time,shotSize,visual,action,dialogue,subtitle,sound,shootingNote,editingNote,isRequired,status。台词必须是老板娘可以直接照着说的完整口语，不得写“介绍一下/展示一下”这种空话。画面必须具体到手机怎么拍，台词必须和画面对应，前3秒必须有强Hook，时间轴必须与总时长匹配。不得拍客人，不得编造销量、评价、价格、经历；未知事实写【需要老板娘确认】。结尾必须有自然CTA。`;
    const result=await callAI(prompt,loadAIConfig());const d=extractJSON<Record<string,unknown>>(result.content);const shots=Array.isArray(d.shots)?d.shots:[];if(shots.length<6)throw new Error("AI返回镜头不足，请再次生成");update({title:String(d.title||active.title),targetUser:String(d.targetUser||active.targetUser),goal:String(d.goal||active.goal),person:String(d.person||active.person),dish:String(d.dish||active.dish),estimatedDuration:String(d.estimatedDuration||active.estimatedDuration),contentType:(d.contentType||active.contentType) as ContentType,shots:shots.map((x,i)=>({...x as Shot,shotNumber:i+1,status:"未拍"})),shootingOrder:String(d.shootingOrder||""),requiredShots:String(d.requiredShots||""),optionalShots:String(d.optionalShots||""),missingMaterials:String(d.missingMaterials||""),status:"草稿"});toast.success("AI已直接生成并写入脚本");}catch(e){toast.error(e instanceof Error?e.message:"AI生成失败");}finally{setBusy(false);}};

  return <div className="space-y-4" data-sm3-page>
    <AIDisconnectedBanner feature="AI脚本导演" />
    <div className="flex items-center justify-between gap-2 flex-wrap"><div><h3 className="text-sm font-medium flex items-center gap-1.5"><Film className="size-4"/>脚本导演（{filtered.length}）</h3><p className="text-[10px] text-muted-foreground">Day{currentDay}：{dayScripts.length}条任务脚本</p></div><div className="flex gap-1.5 flex-wrap"><Button size="sm" variant="outline" onClick={makeToday} disabled={!dayTopic}><Wand2 className="size-3.5 mr-1"/>生成今日脚本</Button><Button size="sm" onClick={newScript}><Plus className="size-3.5 mr-1"/>新建脚本</Button></div></div>
    {filtered.length>0&&<div className="flex gap-1.5 overflow-x-auto pb-1">{filtered.map(s=><button key={s.id} onClick={()=>setActiveId(s.id)} className={`shrink-0 px-3 py-1.5 rounded-md text-xs ${active?.id===s.id?"bg-primary text-primary-foreground":"bg-muted/50"}`}>{s.title.slice(0,12)}{s.day?` · D${s.day}`:" · 自由"}</button>)}</div>}
    {!active?<EmptyState title="暂无脚本" desc="先生成今日脚本或新建自由脚本"/>:<>
      <div className="flex gap-2 flex-wrap"><Button size="sm" variant="outline" onClick={copy}><Copy className="size-3.5 mr-1"/>复制脚本</Button><Button size="sm" variant="outline" onClick={download}><Download className="size-3.5 mr-1"/>下载完整脚本</Button><Button size="sm" variant="outline" onClick={()=>void aiGenerate("重新生成完整脚本") } disabled={busy}><RefreshCw className="size-3.5 mr-1"/>{busy?"AI生成中…":"不满意？重新生成"}</Button><Button size="sm" variant="outline" className="text-destructive" onClick={remove}><Trash2 className="size-3.5 mr-1"/>删除</Button></div>
      {sourceTopic&&<Card className="border-blue-200 bg-blue-50/40"><CardContent className="p-3"><p className="text-[10px] text-blue-600">来源选题</p><p className="text-sm font-medium">{sourceTopic.title}</p><p className="text-xs text-muted-foreground mt-1">Hook：{sourceTopic.hook}</p></CardContent></Card>}
      <Card><CardHeader className="pb-2 cursor-pointer" onClick={()=>setShowMeta(!showMeta)}><CardTitle className="text-sm flex justify-between">脚本信息{showMeta?<ChevronUp className="size-4"/>:<ChevronDown className="size-4"/>}</CardTitle></CardHeader>{showMeta&&<CardContent className="space-y-2"><Input value={active.title} onChange={e=>update({title:e.target.value})} placeholder="视频标题"/><div className="grid grid-cols-2 gap-2"><Input value={active.targetUser} onChange={e=>update({targetUser:e.target.value})} placeholder="目标用户"/><select value={active.contentType} onChange={e=>update({contentType:e.target.value as ContentType})} className="h-9 px-2 rounded-md border bg-background text-sm">{CONTENT_TYPES.map(x=><option key={x}>{x}</option>)}</select></div><div className="grid grid-cols-3 gap-2"><Input value={active.person} onChange={e=>update({person:e.target.value})} placeholder="人物"/><Input value={active.dish} onChange={e=>update({dish:e.target.value})} placeholder="菜品"/><Input value={active.estimatedDuration} onChange={e=>update({estimatedDuration:e.target.value})} placeholder="时长"/></div><Textarea value={active.goal} onChange={e=>update({goal:e.target.value})} rows={2} placeholder="视频目标"/></CardContent>}</Card>
      <Card className="border-primary/20 bg-primary/[0.02]"><CardContent className="p-3 space-y-2"><p className="text-xs font-medium"><Wand2 className="size-3.5 inline mr-1"/>网页内AI导演</p><p className="text-xs text-muted-foreground">不用再复制提示词到外部AI。直接生成、直接覆盖当前脚本；不满意可以再次生成。</p><div className="flex flex-wrap gap-1.5"><Button size="sm" onClick={()=>void aiGenerate("重新生成完整脚本")} disabled={busy}>{busy?"生成中…":"AI重新生成完整脚本"}</Button><Button size="sm" variant="outline" onClick={()=>void aiGenerate("优化前3秒Hook并同步调整相关镜头")} disabled={busy}>优化Hook</Button><Button size="sm" variant="outline" onClick={()=>void aiGenerate("改成老板娘自然口语版")} disabled={busy}>老板娘口语版</Button><Button size="sm" variant="outline" onClick={()=>void aiGenerate("增加冲突和反差但不虚构事实")} disabled={busy}>增加冲突</Button><Button size="sm" variant="outline" onClick={()=>void aiGenerate("压缩成30秒版本")} disabled={busy}>30秒版</Button></div></CardContent></Card>
      <div className="space-y-3">{active.shots.map((x,i)=><Card key={i} className="border-l-4 border-l-primary"><CardContent className="p-3 space-y-2"><div className="flex justify-between gap-2"><div className="flex gap-1.5 items-center"><Badge>镜头{x.shotNumber}</Badge><Badge variant="outline">{x.shotSize||"中景"}</Badge></div><label className="text-[10px] flex items-center gap-1"><input type="checkbox" checked={x.isRequired} onChange={e=>updateShot(i,{isRequired:e.target.checked})}/>必拍</label></div><div className="grid grid-cols-2 gap-2"><Input value={x.time} onChange={e=>updateShot(i,{time:e.target.value})} placeholder="时间"/><Input value={x.shotSize} onChange={e=>updateShot(i,{shotSize:e.target.value})} placeholder="景别"/></div><label className="text-[10px] text-muted-foreground flex items-center gap-1"><Camera className="size-3"/>画面</label><Textarea value={x.visual} onChange={e=>updateShot(i,{visual:e.target.value})} rows={2} placeholder="具体拍什么"/><Input value={x.action} onChange={e=>updateShot(i,{action:e.target.value})} placeholder="人物动作"/><div className="bg-primary/[0.03] p-2 rounded"><label className="text-[10px] text-muted-foreground flex items-center gap-1"><Mic className="size-3"/>台词</label><Textarea value={x.dialogue} onChange={e=>updateShot(i,{dialogue:e.target.value})} rows={3} placeholder="老板娘可以直接照着说的话"/></div><div className="bg-muted/30 p-2 rounded"><label className="text-[10px] text-muted-foreground flex items-center gap-1"><Subtitles className="size-3"/>字幕</label><Input value={x.subtitle} onChange={e=>updateShot(i,{subtitle:e.target.value})}/></div><div className="grid grid-cols-2 gap-2"><Input value={x.sound} onChange={e=>updateShot(i,{sound:e.target.value})} placeholder="声音/BGM"/><Input value={x.editingNote} onChange={e=>updateShot(i,{editingNote:e.target.value})} placeholder="剪辑备注"/></div><Input value={x.shootingNote} onChange={e=>updateShot(i,{shootingNote:e.target.value})} placeholder="拍摄备注"/><Button size="sm" variant={x.status==="已拍"?"default":"outline"} onClick={()=>updateShot(i,{status:x.status==="已拍"?"未拍":"已拍"})}>{x.status==="已拍"?<><Check className="size-3 mr-1"/>已拍</>:"标记已拍"}</Button></CardContent></Card>)}</div>
      <Card><CardHeader className="pb-2"><CardTitle className="text-sm">拍摄总结</CardTitle></CardHeader><CardContent className="space-y-2"><Textarea value={active.shootingOrder} onChange={e=>update({shootingOrder:e.target.value})} placeholder="拍摄顺序" rows={2}/><Textarea value={active.requiredShots} onChange={e=>update({requiredShots:e.target.value})} placeholder="必拍镜头清单" rows={2}/><Textarea value={active.optionalShots} onChange={e=>update({optionalShots:e.target.value})} placeholder="可选镜头" rows={2}/><Textarea value={active.missingMaterials} onChange={e=>update({missingMaterials:e.target.value})} placeholder="缺失素材" rows={2}/><FactConfirmTag text="具体价格、时间、经历、销量等事实必须老板娘确认后再拍"/></CardContent></Card>
    </>}
  </div>;
}
